name: chunk_up
description: "A vocabulary chunking application for language learning"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.29.3"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.71.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  excel: ^4.0.6
  file_picker: ^10.1.5
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  uuid: ^4.5.1
  pluralize: ^0.0.8
  timezone: ^0.10.0
  
  # 새로 추가된 패키지
  flutter_riverpod: ^2.6.1             # Riverpod 상태 관리
  freezed_annotation: ^3.0.0          # Freezed 애노테이션
  json_annotation: ^4.9.0             # JSON 직렬화 애노테이션
  hooks_riverpod: ^2.6.1              # Hook과 Riverpod 통합
  pdf: ^3.11.3                       # PDF 문서 생성
  printing: ^5.14.2                  # PDF 인쇄 및 공유
  crypto: ^3.0.6                     # 암호화 및 해시 기능
  encrypt: ^5.0.3                    # 암호화 라이브러리
  confetti: ^0.7.0                   # 축하 애니메이션
  in_app_purchase: ^3.2.2            # 인앱 구매 및 구독
  google_sign_in: ^6.3.0             # 구글 계정 로그인
  google_mobile_ads: ^6.0.0          # 구글 AdMob
  googleapis: ^14.0.0                # 구글 API (드라이브 등)
  
  # Firebase 패키지들
  firebase_core: ^3.8.0             # Firebase 핵심 패키지
  cloud_functions: ^5.2.0           # Firebase Cloud Functions
  firebase_auth: ^5.3.3             # Firebase 인증
  cloud_firestore: ^5.5.1          # Cloud Firestore 데이터베이스


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # 기본 아이콘 이미지
  adaptive_icon_background: "#FFFFFF"  # 배경색 (원하는 색상으로 변경 가능)
  adaptive_icon_foreground: "assets/icons/app_icon.png"  # 전경 이미지로 동일한 이미지 사용
  remove_alpha_ios: true  # iOS에서 투명도 제거 (더 선명한 이미지)
  min_sdk_android: 23  # 최소 Android SDK 버전


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 테스트 패키지
  mockito: ^5.4.4                     # Mock 객체 생성
  integration_test:                   # E2E 테스트
    sdk: flutter
  
  # 새로 추가된 개발 패키지
  build_runner: ^2.4.8                # 코드 생성 도구
  freezed: ^3.0.0                     # 불변 객체 코드 생성
  json_serializable: ^6.8.0           # JSON 직렬화 코드 생성
  riverpod_lint: ^2.3.13             # Riverpod 린트 규칙
  custom_lint: ^0.7.5                # 커스텀 린트 도구

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package